# task: classification
# Version: 1.0
data_path: D:\Dataset\UCMerced_LandUse_Dataset\Images
connected_csv_path: docs/data.csv
index_name: image_path

target_label: ground_truth

train_radio: 0.5

# Number of classes
num_classes: 21
# Training configuration root keys below:
# - epochs
# - batch_size
epochs: 3
# Batch size for training
batch_size: 128

optimizer:
  name: adam
  # Learning rate
  learning_rate: 0.0001
  step_size: 50
  gamma: 0.8

model:
  name: vit_small_patch16_224
  pretrain: false
  pretrain_weight_path: ''

train_valid_dir: ''
save_dir: ''

# label info:
# - Keys are class indices
# - Values are class names
label:
  0: agricultural
  1: airplane
  2: baseballdiamond
  3: beach
  4: buildings
  5: chaparral
  6: denseresidential
  7: forest
  8: freeway
  9: golfcourse
  10: harbor
  11: intersection
  12: mediumresidential
  13: mobilehomepark
  14: overpass
  15: parkinglot
  16: river
  17: runway
  18: sparseresidential
  19: storagetanks
  20: tenniscourt
